#!/bin/bash
# ============================================================
# activate.sh -- find conda and activate this project's environment. Sourced by each sbatch
# script.
#
# Use it like this from a script (three lines, independent of how deep the script sits;
# sbatch copies the script into spool, so $0 cannot be used to locate anything and
# $SLURM_SUBMIT_DIR, which sbatch sets, has to be used instead):
#
#   _d="${SLURM_SUBMIT_DIR:-$PWD}"
#   while [ ! -f "$_d/activate.sh" ] && [ "$_d" != / ]; do _d=$(dirname "$_d"); done
#   source "$_d/activate.sh"
#
# After sourcing, $REPO (the repo root) is available. Environment location, in order of
# precedence:
#   1. $OCEAN_ENV                              set explicitly
#   2. OCEAN_ENV= in <repo>/.env.local         generated by setup.sh, not committed
#   3. /nfs/hpc/share/$USER/.conda/envs/ocean  the default location on the cluster
#
# No home directory or username is hard-coded here -- clone it under a different account and
# it still runs.
# ============================================================

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export REPO

# The cluster's shared conda (not a personal path). Elsewhere it can be overridden with CONDA_SH=.
CONDA_SH="${CONDA_SH:-/nfs/stak/a1/rhel5apps/conda/24.3/etc/profile.d/conda.sh}"
if [ ! -f "$CONDA_SH" ]; then
  echo "activate.sh: conda not found ($CONDA_SH). Run $REPO/setup.sh first" >&2
  return 1 2>/dev/null || exit 1
fi
# shellcheck disable=SC1090
source "$CONDA_SH"

[ -f "$REPO/.env.local" ] && source "$REPO/.env.local"
OCEAN_ENV="${OCEAN_ENV:-/nfs/hpc/share/$USER/.conda/envs/ocean}"

if [ ! -x "$OCEAN_ENV/bin/python" ]; then
  echo "activate.sh: environment does not exist: $OCEAN_ENV" >&2
  echo "            run $REPO/setup.sh first (or come back with OCEAN_ENV=<your env>)" >&2
  return 1 2>/dev/null || exit 1
fi
conda activate "$OCEAN_ENV"
