// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `results/web/model/` 下的一个 checkpoint。
 */
export type Checkpoint = { 
/**
 * run 名，如 `hpm_fw_aU_h128`
 */
run_name: string, 
/**
 * 时间戳目录，如 `2026-08-12_15-31-45`
 */
run_ts: string, 
/**
 * 权重文件名，如 `best.pt`
 */
file: string, bytes: number, 
/**
 * 是不是当前锁定在用的那个
 */
current: boolean, };
