// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobStatus = { job_id: string, 
/**
 * PENDING / RUNNING / COMPLETED / FAILED / ...
 */
state: string, partition: string, 
/**
 * `squeue` 的 %M（已跑时长）或 sacct 的 Elapsed
 */
elapsed: string, 
/**
 * 还在队列里 = true；已经归档 = false
 */
live: boolean, };
