// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageRun = { 
/**
 * funwave | prior | vis
 */
kind: string, job_id: string, partition: string, 
/**
 * SLURM 状态，由轮询更新；刚提交时是 UNKNOWN
 */
state: string, elapsed: string, };
