// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageRun } from "./StageRun";

export type Submission = { id: string, created_at: number, 
/**
 * 造波机振幅 AMP_WK（m）。波高 H = 2·amp
 */
amp: number, slope: number, slope_label: string, 
/**
 * 算例目录名
 */
case: string, 
/**
 * true = 命中已有算例，FUNWAVE 那段跳过了
 */
reused_funwave: boolean, chunk: number, fields: Array<string>, stages: Array<StageRun>, 
/**
 * queued | running | done | failed | cancelled
 */
status: string, 
/**
 * 当前跑到哪一段：funwave | prior | vis | ""
 */
stage: string, 
/**
 * 失败时的说明
 */
note: string | null, };
