// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Submission } from "./Submission";

/**
 * `/api/submissions` 的返回。
 *
 * **记录本身来自本地的 `submissions.json`，不依赖集群** —— 所以它总是立刻返回。
 * 跟集群对齐是后台在做的事，`syncing` 让前端能把这件事显示出来，而不是
 * 拿整个列表去等一次可能很慢的 ssh。
 */
export type SubmissionList = { items: Array<Submission>, 
/**
 * 正在跟集群对齐
 */
syncing: boolean, 
/**
 * 上一次成功对齐的时刻；从没对齐过是 None
 */
synced_at: number | null, };
